### ISSUE TITLE
Not working with Snowdog Alpaca theme

### ISSUE THREAD

**Issue by henkvalk** [magepow/magento2-infinitescroll#2]
Thanks for share this module. 

I tried to use it in the [Alpaca Theme](https://github.com/SnowdogApps/magento2-alpaca-theme/) and changed the Selector for pagination in the backend to `.pager__list` . The button will show up at the bottom of the category-list, but after loading the products from page 2 or not showing up.

**Comment by magiccart** [comment]
@henkvalk We need a demo to check this. Can you create a ticket here https://magepow.com/ticket/ and provide info our developer will help check it?

**Comment by magiccart** [comment]
@henkvalk I have tried installed on Snowdog Alpaca theme it still works fine.
