### ISSUE TITLE
Resetting infinite scroll after ajax call

### ISSUE THREAD

**Issue by ktsixit** [magepow/magento2-infinitescroll#7]
This is a question, not really an issue.
I'd like to ask how can I reset infinite scroll after updating product list via ajax.
Loaded product use paging instead of infinite scroll, so I guess that a simple function call to extension javascipt would solve that.
Thank you in advance.

**Comment by ga3003** [comment]
I have the same question. I am using Ajax for layered navigation and found it's not working after applying filters on products.

**Comment by magiccart** [comment]
@ktsixit @ga3003 can call code below

$('body').trigger('collectionUpdated');
